### ISSUE TITLE
After mitochondrial genome assembly

### ISSUE THREAD

**Issue by u2sj** [pedronachtigall/MITGARD#5]
I am a novice, and what I would like to ask is how to proceed with the analysis process after obtaining a FASTA file? I want to study the changes in mitochondrial in tumors.

**Comment by pedronachtigall** [comment]
Hi @u2sj ,
Thank you for using MITGARD in your analysis.
There is a plethora of analysis that can be performed after retrieving the mitogenome.
The next steps will be totally related to your project's objective and to answer biological questions in your project.
I strongly recommend you to discuss it with your research group/supervisor/project manager to decide the next steps.
Good luck.
